import Foundation

/// Apple's list of commonly-used third-party SDKs that must ship a signed
/// privacy manifest.
///
/// Source: https://developer.apple.com/support/third-party-SDK-requirements/
/// Last reviewed: 2026-06 (update monthly). The list below is a representative
/// subset for the scaffold and will be completed when the resolver is built.
public enum ThirdPartySDKList {
    /// Canonical SDK names as published by Apple.
    public static let required: Set<String> = [
        "Abseil",
        "AFNetworking",
        "Alamofire",
        "AppAuth",
        "BoringSSL / openssl_grpc",
        "Capacitor",
        "Charts",
        "connectivity_plus",
        "Cordova",
        "device_info_plus",
        "DKImagePickerController",
        "DKPhotoGallery",
        "FBAEMKit",
        "FBLPromises",
        "FBSDKCoreKit",
        "Firebase",
        "FirebaseABTesting",
        "FirebaseAuth",
        "FirebaseCore",
        "FirebaseCrashlytics",
        "FirebaseInstallations",
        "FirebaseMessaging",
        "FirebaseRemoteConfig",
        "Flutter",
        "fluttertoast",
        "FMDB",
        "geolocator_apple",
        "GoogleDataTransport",
        "GoogleSignIn",
        "GoogleToolboxForMac",
        "GoogleUtilities",
        "grpcpp",
        "GTMAppAuth",
        "GTMSessionFetcher",
        "hermes",
        "image_picker_ios",
        "IQKeyboardManager",
        "IQKeyboardManagerSwift",
        "Kingfisher",
        "leveldb",
        "Lottie",
        "MBProgressHUD",
        "nanopb",
        "OneSignal",
        "OneSignalCore",
        "OpenSSL",
        "OrderedSet",
        "package_info",
        "package_info_plus",
        "path_provider",
        "path_provider_ios",
        "Promises",
        "Protobuf",
        "Reachability",
        "RealmSwift",
        "RxCocoa",
        "RxRelay",
        "RxSwift",
        "SDWebImage",
        "share_plus",
        "shared_preferences_ios",
        "SnapKit",
        "sqflite",
        "Starscream",
        "SVProgressHUD",
        "SwiftyGif",
        "SwiftyJSON",
        "Toast",
        "UnityFramework",
        "url_launcher",
        "url_launcher_ios",
        "video_player_avfoundation",
        "wakelock",
        "webview_flutter_wkwebview"
    ]
}
